# Generated by Django 5.1.4 on 2025-05-10 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='engine_app/project_images/')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='engine_app.project')),
            ],
            options={
                'verbose_name': 'Project Gallery',
                'verbose_name_plural': 'Project Galleries',
                'db_table': 'project_gallery',
            },
        ),
    ]
